# Generated by Django 5.0.7 on 2024-07-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pdf',
            field=models.FileField(default=0, upload_to='skills/pdf/'),
            preserve_default=False,
        ),
    ]
